const products = [
    {
        id: 301,
        name: "USB-C Charger 1",
        category: "Accessories",
        brand: "Anker",
        price: 7990,
        stock: 100,
        description:
            "Fast-charging USB-C wall charger compatible with most devices.",
        description_hu: "Gyors USB-C fali töltő, kompatibilis a legtöbb eszközzel.",
        specifications: {
            output_power: "20W",
            port_type: "USB-C",
            compatibility: "Universal",
        },
        sales: { "2024-11-22": 9, "2024-11-09": 8, "2024-11-17": 9 },
    },
    {
        id: 302,
        name: "Wireless Earbuds 2",
        category: "Audio",
        brand: "JBL",
        price: 26090,
        stock: 48,
        description: "Comfortable and long-lasting wireless earbuds with great sound.",
        description_hu: "Kényelmes és tartós vezeték nélküli fülhallgató kiváló hangzással.",
        specifications: {
            battery_life: "8 hours",
            connectivity: "Bluetooth 5.0",
            water_resistance: "IPX4",
        },
        sales: {
            "2024-11-16": 1,
            "2024-11-28": 4,
            "2024-11-04": 6,
            "2024-11-15": 9,
        },
    },
    {
        id: 303,
        name: "Portable Power Bank 3",
        category: "Accessories",
        brand: "Xiaomi",
        price: 15190,
        stock: 116,
        description:
            "High-capacity portable power bank with USB-C and USB-A ports.",
        description_hu:
            "Nagy kapacitású hordozható töltő USB-C és USB-A portokkal.",
        specifications: {
            capacity: "20,000mAh",
            ports: "USB-C, USB-A",
            compatibility: "Universal",
        },
        sales: {
            "2024-11-24": 5,
            "2024-11-11": 3,
            "2024-11-15": 3,
            "2024-11-12": 4,
        },
    },
    {
        id: 304,
        name: "Smartphone Screen Protector 4",
        category: "Accessories",
        brand: "Belkin",
        price: 5290,
        stock: 194,
        description: "Tempered glass screen protector for smartphones.",
        description_hu: "Edzett üveg kijelzővédő okostelefonokhoz.",
        specifications: {
            material: "Tempered glass",
            compatibility: "Universal",
            thickness: "0.33mm",
        },
        sales: {
            "2024-11-20": 4,
            "2024-11-06": 2,
            "2024-11-11": 6,
            "2024-11-30": 4,
            "2024-11-25": 6,
        },
    },
    {
        id: 305,
        name: "Smartwatch Band 5",
        category: "Accessories",
        brand: "Fitbit",
        price: 13390,
        stock: 72,
        description: "Comfortable and stylish smartwatch band.",
        description_hu: "Kényelmes és divatos okosóra szíj.",
        specifications: {
            material: "Silicone",
            compatibility: "Fitbit Versa 3, Sense",
            adjustable: "Yes",
        },
        sales: { "2024-11-09": 5, "2024-11-25": 1, "2024-11-07": 6 },
    },
    {
        id: 306,
        name: "USB-C Charger 6",
        category: "Accessories",
        brand: "Anker",
        price: 8490,
        stock: 90,
        description:
            "Fast-charging USB-C wall charger compatible with most devices.",
        description_hu: "Gyors USB-C fali töltő, kompatibilis a legtöbb eszközzel.",
        specifications: {
            output_power: "20W",
            port_type: "USB-C",
            compatibility: "Universal",
        },
        sales: { "2024-11-23": 9, "2024-11-04": 3, "2024-11-27": 4 },
    },
    {
        id: 307,
        name: "Wireless Earbuds 7",
        category: "Audio",
        brand: "JBL",
        price: 26590,
        stock: 38,
        description:
            "Comfortable and long-lasting wireless earbuds with great sound.",
        description_hu:
            "Kényelmes és tartós vezeték nélküli fülhallgató kiváló hangzással.",
        specifications: {
            battery_life: "8 hours",
            connectivity: "Bluetooth 5.0",
            water_resistance: "IPX4",
        },
        sales: { "2024-11-14": 4, "2024-11-11": 5 },
    },
    {
        id: 308,
        name: "Portable Power Bank 8",
        category: "Accessories",
        brand: "Xiaomi",
        price: 15690,
        stock: 106,
        description:
            "High-capacity portable power bank with USB-C and USB-A ports.",
        description_hu:
            "Nagy kapacitású hordozható töltő USB-C és USB-A portokkal.",
        specifications: {
            capacity: "20,000mAh",
            ports: "USB-C, USB-A",
            compatibility: "Universal",
        },
        sales: {
            "2024-11-14": 3,
            "2024-11-06": 10,
            "2024-11-29": 6,
            "2024-11-25": 5,
        },
    },
    {
        id: 309,
        name: "Smartphone Screen Protector 9",
        category: "Accessories",
        brand: "Belkin",
        price: 5790,
        stock: 184,
        description: "Tempered glass screen protector for smartphones.",
        description_hu: "Edzett üveg kijelzővédő okostelefonokhoz.",
        specifications: {
            material: "Tempered glass",
            compatibility: "Universal",
            thickness: "0.33mm",
        },
        sales: {
            "2024-11-19": 5,
            "2024-11-26": 7,
            "2024-11-23": 6,
            "2024-11-06": 3,
        },
    },
    {
        id: 310,
        name: "Smartwatch Band 10",
        category: "Accessories",
        brand: "Fitbit",
        price: 13890,
        stock: 62,
        description: "Comfortable and stylish smartwatch band.",
        description_hu: "Kényelmes és divatos okosóra szíj.",
        specifications: {
            material: "Silicone",
            compatibility: "Fitbit Versa 3, Sense",
            adjustable: "Yes",
        },
        sales: {
            "2024-11-18": 5,
            "2024-11-22": 9,
            "2024-11-27": 5,
            "2024-11-21": 7,
            "2024-11-08": 9,
        },
    },
    {
        id: 311,
        name: "USB-C Charger 11",
        category: "Accessories",
        brand: "Anker",
        price: 8990,
        stock: 80,
        description:
            "Fast-charging USB-C wall charger compatible with most devices.",
        description_hu: "Gyors USB-C fali töltő, kompatibilis a legtöbb eszközzel.",
        specifications: {
            output_power: "20W",
            port_type: "USB-C",
            compatibility: "Universal",
        },
        sales: {
            "2024-11-10": 2,
            "2024-11-19": 4,
            "2024-11-12": 1,
            "2024-11-07": 1,
            "2024-11-11": 9,
        },
    },
    {
        id: 312,
        name: "Wireless Earbuds 12",
        category: "Audio",
        brand: "JBL",
        price: 27090,
        stock: 0,
        description:
            "Comfortable and long-lasting wireless earbuds with great sound.",
        description_hu:
            "Kényelmes és tartós vezeték nélküli fülhallgató kiváló hangzással.",
        specifications: {
            battery_life: "8 hours",
            connectivity: "Bluetooth 5.0",
            water_resistance: "IPX4",
        },
        sales: {
            "2024-11-15": 8,
            "2024-11-10": 6,
            "2024-11-06": 4,
            "2024-11-24": 5,
            "2024-11-25": 3,
            "2024-11-05": 6,
        },
    },
    {
        id: 313,
        name: "Portable Power Bank 13",
        category: "Accessories",
        brand: "Xiaomi",
        price: 16190,
        stock: 96,
        description:
            "High-capacity portable power bank with USB-C and USB-A ports.",
        description_hu:
            "Nagy kapacitású hordozható töltő USB-C és USB-A portokkal.",
        specifications: {
            capacity: "20,000mAh",
            ports: "USB-C, USB-A",
            compatibility: "Universal",
        },
        sales: { "2024-11-01": 3, "2024-11-27": 9, "2024-11-06": 8 },
    },
    {
        id: 314,
        name: "Smartphone Screen Protector 14",
        category: "Accessories",
        brand: "Belkin",
        price: 6290,
        stock: 174,
        description: "Tempered glass screen protector for smartphones.",
        description_hu: "Edzett üveg kijelzővédő okostelefonokhoz.",
        specifications: {
            material: "Tempered glass",
            compatibility: "Universal",
            thickness: "0.33mm",
        },
        sales: {
            "2024-11-23": 3,
            "2024-11-14": 4,
            "2024-11-25": 2,
            "2024-11-28": 9,
        },
    },
    {
        id: 315,
        name: "Smartwatch Band 15",
        category: "Accessories",
        brand: "Fitbit",
        price: 14390,
        stock: 52,
        description: "Comfortable and stylish smartwatch band.",
        description_hu: "Kényelmes és divatos okosóra szíj.",
        specifications: {
            material: "Silicone",
            compatibility: "Fitbit Versa 3, Sense",
            adjustable: "Yes",
        },
        sales: {
            "2024-11-02": 5,
            "2024-11-25": 7,
            "2024-11-26": 9,
            "2024-11-13": 10,
            "2024-11-08": 1,
        },
    },
    {
        id: 316,
        name: "USB-C Charger 16",
        category: "Accessories",
        brand: "Anker",
        price: 9490,
        stock: 70,
        description:
            "Fast-charging USB-C wall charger compatible with most devices.",
        description_hu: "Gyors USB-C fali töltő, kompatibilis a legtöbb eszközzel.",
        specifications: {
            output_power: "20W",
            port_type: "USB-C",
            compatibility: "Universal",
        },
        sales: { "2024-11-21": 2, "2024-11-24": 3 },
    },
    {
        id: 317,
        name: "Wireless Earbuds 17",
        category: "Audio",
        brand: "JBL",
        price: 27590,
        stock: 0,
        description:
            "Comfortable and long-lasting wireless earbuds with great sound.",
        description_hu:
            "Kényelmes és tartós vezeték nélküli fülhallgató kiváló hangzással.",
        specifications: {
            battery_life: "8 hours",
            connectivity: "Bluetooth 5.0",
            water_resistance: "IPX4",
        },
        sales: {
            "2024-11-08": 2,
            "2024-11-14": 10,
            "2024-11-19": 6,
            "2024-11-15": 2,
            "2024-11-23": 3,
            "2024-11-26": 9,
        },
    },
    {
        id: 318,
        name: "Portable Power Bank 18",
        category: "Accessories",
        brand: "Xiaomi",
        price: 16690,
        stock: 86,
        description:
            "High-capacity portable power bank with USB-C and USB-A ports.",
        description_hu:
            "Nagy kapacitású hordozható töltő USB-C és USB-A portokkal.",
        specifications: {
            capacity: "20,000mAh",
            ports: "USB-C, USB-A",
            compatibility: "Universal",
        },
        sales: {
            "2024-11-24": 1,
            "2024-11-13": 7,
            "2024-11-29": 7,
            "2024-11-06": 3,
            "2024-11-10": 2,
            "2024-11-22": 6,
        },
    },
    {
        id: 319,
        name: "Smartphone Screen Protector 19",
        category: "Accessories",
        brand: "Belkin",
        price: 6790,
        stock: 164,
        description: "Tempered glass screen protector for smartphones.",
        description_hu: "Edzett üveg kijelzővédő okostelefonokhoz.",
        specifications: {
            material: "Tempered glass",
            compatibility: "Universal",
            thickness: "0.33mm",
        },
        sales: { "2024-11-11": 10, "2024-11-22": 7, "2024-11-18": 6 },
    },
    {
        id: 320,
        name: "Smartwatch Band 20",
        category: "Accessories",
        brand: "Fitbit",
        price: 14890,
        stock: 42,
        description: "Comfortable and stylish smartwatch band.",
        description_hu: "Kényelmes és divatos okosóra szíj.",
        specifications: {
            material: "Silicone",
            compatibility: "Fitbit Versa 3, Sense",
            adjustable: "Yes",
        },
        sales: {
            "2024-11-11": 10,
            "2024-11-23": 4,
            "2024-11-06": 3,
            "2024-11-28": 3,
        },
    },
    {
        id: 321,
        name: "USB-C Charger 21",
        category: "Accessories",
        brand: "Anker",
        price: 9990,
        stock: 0,
        description:
            "Fast-charging USB-C wall charger compatible with most devices.",
        description_hu: "Gyors USB-C fali töltő, kompatibilis a legtöbb eszközzel.",
        specifications: {
            output_power: "20W",
            port_type: "USB-C",
            compatibility: "Universal",
        },
        sales: { "2024-11-05": 2, "2024-11-19": 10, "2024-11-26": 3 },
    },
    {
        id: 322,
        name: "Wireless Earbuds 22",
        category: "Audio",
        brand: "JBL",
        price: 28090,
        stock: 8,
        description:
            "Comfortable and long-lasting wireless earbuds with great sound.",
        description_hu:
            "Kényelmes és tartós vezeték nélküli fülhallgató kiváló hangzással.",
        specifications: {
            battery_life: "8 hours",
            connectivity: "Bluetooth 5.0",
            water_resistance: "IPX4",
        },
        sales: {
            "2024-11-08": 3,
            "2024-11-17": 8,
            "2024-11-02": 2,
            "2024-11-25": 8,
            "2024-11-09": 3,
        },
    },
    {
        id: 323,
        name: "Portable Power Bank 23",
        category: "Accessories",
        brand: "Xiaomi",
        price: 17190,
        stock: 76,
        description:
            "High-capacity portable power bank with USB-C and USB-A ports.",
        description_hu:
            "Nagy kapacitású hordozható töltő USB-C és USB-A portokkal.",
        specifications: {
            capacity: "20,000mAh",
            ports: "USB-C, USB-A",
            compatibility: "Universal",
        },
        sales: {
            "2024-11-23": 10,
            "2024-11-30": 10,
            "2024-11-09": 3,
            "2024-11-21": 6,
        },
    },
    {
        id: 324,
        name: "Smartphone Screen Protector 24",
        category: "Accessories",
        brand: "Belkin",
        price: 7290,
        stock: 154,
        description: "Tempered glass screen protector for smartphones.",
        description_hu: "Edzett üveg kijelzővédő okostelefonokhoz.",
        specifications: {
            material: "Tempered glass",
            compatibility: "Universal",
            thickness: "0.33mm",
        },
        sales: {
            "2024-11-26": 3,
            "2024-11-25": 5,
            "2024-11-14": 3,
            "2024-11-24": 9,
        },
    },
    {
        id: 325,
        name: "Smartwatch Band 25",
        category: "Accessories",
        brand: "Fitbit",
        price: 15390,
        stock: 32,
        description: "Comfortable and stylish smartwatch band.",
        description_hu: "Kényelmes és divatos okosóra szíj.",
        specifications: {
            material: "Silicone",
            compatibility: "Fitbit Versa 3, Sense",
            adjustable: "Yes",
        },
        sales: {
            "2024-11-08": 8,
            "2024-11-20": 3,
            "2024-11-24": 9,
            "2024-11-29": 1,
            "2024-11-01": 4,
            "2024-11-21": 3,
        },
    },
];
